export default {
    CA: {
        AB: "Alberta",
        BC: "British Columbia",
        MB: "Manitoba",
        NS: "Nova Scotia",
        ON: "Ontario",
        QC: "Quebec",
        SK: "Saskatchewan",
    },
    FR: {
        ARA: "Auvergne-Rhône-Alpes",
        BFC: "Bourgogne-Franche-Comté",
        CVL: "Centre",
        GES: "Grand Est",
        HDF: "Hauts-de-France",
        IDF: "Île-de-France",
        NAQ: "Nouvelle-Aquitaine",
        OCC: "Occitanie",
        PAC: "Provence-Alpes-Côte d'Azur",
        PDL: "Pays de la Loire",
    },
    // AU: {
    //     ACT: "Australian Capital Territory",
    //     NSW: "New South Wales",
    //     NT: "Northern Territory",
    //     QLD: "Queensland",
    //     SA: "South Australia",
    //     TAS: "Tasmania",
    //     VIC: "Victoria",
    //     WA: "Western Australia",
    // },
    // CN: {
    //     安徽省: "安徽省 - Anhui Sheng",
    //     澳门: "澳门 - Macau",
    //     北京市: "北京市 - Beijing Shi",
    //     重庆市: "重庆市 - Chongqing Shi",
    //     福建省: "福建省 - Fujian Sheng",
    //     甘肃省: "甘肃省 - Gansu Sheng",
    //     广东省: "广东省 - Guangdong Sheng",
    //     广西壮族自治区: "广西 - Guangxi Zhuangzuzizhiqu",
    //     贵州省: "贵州省 - Guizhou Sheng",
    //     海南省: "海南省 - Hainan Sheng",
    //     河北省: "河北省 - Hebei Sheng",
    //     河南省: "河南省 - Henan Sheng",
    //     黑龙江省: "黑龙江省 - Heilongjiang Sheng",
    //     湖北省: "湖北省 - Hubei Sheng",
    //     湖南省: "湖南省 - Hunan Sheng",
    //     吉林省: "吉林省 - Jilin Sheng",
    //     江苏省: "江苏省 - Jiangsu Sheng",
    //     江西省: "江西省 - Jiangxi Sheng",
    //     辽宁省: "辽宁省 - Liaoning Sheng",
    //     内蒙古自治区: "内蒙古 - Neimenggu Zizhiqu",
    //     宁夏回族自治区: "宁夏 - Ningxia Huizuzizhiqu",
    //     青海省: "青海省 - Qinghai Sheng",
    //     山东省: "山东省 - Shandong Sheng",
    //     山西省: "山西省 - Shanxi Sheng",
    //     陕西省: "陕西省 - Shaanxi Sheng",
    //     上海市: "上海市 - Shanghai Shi",
    //     四川省: "四川省 - Sichuan Sheng",
    //     台湾: "台湾 - Taiwan",
    //     天津市: "天津市 - Tianjin Shi",
    //     西藏自治区: "西藏 - Xizang Zizhiqu",
    //     香港: "香港 - Hong Kong",
    //     新疆维吾尔自治区: "新疆 - Xinjiang Weiwuerzizhiqu",
    //     云南省: "云南省 - Yunnan Sheng",
    //     浙江省: "浙江省 - Zhejiang Sheng",
    // },
    // HK: {
    //     Kowloon: "九龍 - Kowloon",
    //     "Hong Kong": "香港島 - Hong Kong",
    //     "New Territories": "新界 - New Territories",
    // },
    // IT: {
    //     AG: "Agrigento",
    //     AL: "Alessandria",
    //     AN: "Ancona",
    //     AO: "Aosta",
    //     AR: "Arezzo",
    //     AP: "Ascoli Piceno",
    //     AT: "Asti",
    //     AV: "Avellino",
    //     BA: "Bari",
    //     BT: "Barletta-Andria-Trani",
    //     BL: "Belluno",
    //     BN: "Benevento",
    //     BG: "Bergamo",
    //     BI: "Biella",
    //     BO: "Bologna",
    //     BZ: "Bolzano",
    //     BS: "Brescia",
    //     BR: "Brindisi",
    //     CA: "Cagliari",
    //     CL: "Caltanissetta",
    //     CB: "Campobasso",
    //     CI: "Carbonia-Iglesias",
    //     CE: "Caserta",
    //     CT: "Catania",
    //     CZ: "Catanzaro",
    //     CH: "Chieti",
    //     CO: "Como",
    //     CS: "Cosenza",
    //     CR: "Cremona",
    //     KR: "Crotone",
    //     CN: "Cuneo",
    //     EN: "Enna",
    //     FM: "Fermo",
    //     FE: "Ferrara",
    //     FI: "Firenze",
    //     FG: "Foggia",
    //     FC: "Forlì-Cesena",
    //     FR: "Frosinone",
    //     GE: "Genova",
    //     GO: "Gorizia",
    //     GR: "Grosseto",
    //     IM: "Imperia",
    //     IS: "Isernia",
    //     AQ: "L'Aquila",
    //     SP: "La Spezia",
    //     LT: "Latina",
    //     LE: "Lecce",
    //     LC: "Lecco",
    //     LI: "Livorno",
    //     LO: "Lodi",
    //     LU: "Lucca",
    //     MC: "Macerata",
    //     MN: "Mantova",
    //     MS: "Massa-Carrara",
    //     MT: "Matera",
    //     VS: "Medio Campidano",
    //     ME: "Messina",
    //     MI: "Milano",
    //     MO: "Modena",
    //     MB: "Monza e Brianza",
    //     NA: "Napoli",
    //     NO: "Novara",
    //     NU: "Nuoro",
    //     OG: "Ogliastra",
    //     OT: "Olbia-Tempio",
    //     OR: "Oristano",
    //     PD: "Padova",
    //     PA: "Palermo",
    //     PR: "Parma",
    //     PV: "Pavia",
    //     PG: "Perugia",
    //     PU: "Pesaro e Urbino",
    //     PE: "Pescara",
    //     PC: "Piacenza",
    //     PI: "Pisa",
    //     PT: "Pistoia",
    //     PN: "Pordenone",
    //     PZ: "Potenza",
    //     PO: "Prato",
    //     RG: "Ragusa",
    //     RA: "Ravenna",
    //     RC: "Reggio Calabria",
    //     RE: "Reggio Emilia",
    //     RI: "Rieti",
    //     RN: "Rimini",
    //     RM: "Roma",
    //     RO: "Rovigo",
    //     SA: "Salerno",
    //     SS: "Sassari",
    //     SV: "Savona",
    //     SI: "Siena",
    //     SR: "Siracusa",
    //     SO: "Sondrio",
    //     SD: "Sud Sardegna",
    //     TA: "Taranto",
    //     TE: "Teramo",
    //     TR: "Terni",
    //     TO: "Torino",
    //     TP: "Trapani",
    //     TN: "Trento",
    //     TV: "Treviso",
    //     TS: "Trieste",
    //     UD: "Udine",
    //     VA: "Varese",
    //     VE: "Venezia",
    //     VB: "Verbano-Cusio-Ossola",
    //     VC: "Vercelli",
    //     VR: "Verona",
    //     VV: "Vibo Valentia",
    //     VI: "Vicenza",
    //     VT: "Viterbo",
    // },
    // JP: {
    //     北海道: "北海道 - Hokkaido",
    //     青森県: "青森県 - Aomori",
    //     岩手県: "岩手県 - Iwate",
    //     宮城県: "宮城県 - Miyagi",
    //     秋田県: "秋田県 - Akita",
    //     山形県: "山形県 - Yamagata",
    //     福島県: "福島県 - Fukushima",
    //     茨城県: "茨城県 - Ibaraki",
    //     栃木県: "栃木県 - Tochigi",
    //     群馬県: "群馬県 - Gunma",
    //     埼玉県: "埼玉県 - Saitama",
    //     千葉県: "千葉県 - Chiba",
    //     東京都: "東京都 - Tokyo",
    //     神奈川県: "神奈川県 - Kanagawa",
    //     新潟県: "新潟県 - Niigata",
    //     富山県: "富山県 - Toyama",
    //     石川県: "石川県 - Ishikawa",
    //     福井県: "福井県 - Fukui",
    //     山梨県: "山梨県 - Yamanashi",
    //     長野県: "長野県 - Nagano",
    //     岐阜県: "岐阜県 - Gifu",
    //     静岡県: "静岡県 - Shizuoka",
    //     愛知県: "愛知県 - Aichi",
    //     三重県: "三重県 - Mie",
    //     滋賀県: "滋賀県 - Shiga",
    //     京都府: "京都府 - Kyoto",
    //     大阪府: "大阪府 - Osaka",
    //     兵庫県: "兵庫県 - Hyogo",
    //     奈良県: "奈良県 - Nara",
    //     和歌山県: "和歌山県 - Wakayama",
    //     鳥取県: "鳥取県 - Tottori",
    //     島根県: "島根県 - Shimane",
    //     岡山県: "岡山県 - Okayama",
    //     広島県: "広島県 - Hiroshima",
    //     山口県: "山口県 - Yamaguchi",
    //     徳島県: "徳島県 - Tokushima",
    //     香川県: "香川県 - Kagawa",
    //     愛媛県: "愛媛県 - Ehime",
    //     高知県: "高知県 - Kochi",
    //     福岡県: "福岡県 - Fukuoka",
    //     佐賀県: "佐賀県 - Saga",
    //     長崎県: "長崎県 - Nagasaki",
    //     熊本県: "熊本県 - Kumamoto",
    //     大分県: "大分県 - Oita",
    //     宮崎県: "宮崎県 - Miyazaki",
    //     鹿児島県: "鹿児島県 - Kagoshima",
    //     沖縄県: "沖縄県 - Okinawa",
    // },
    // KR: {
    //     강원도: "강원 - Gangwon-do",
    //     경기도: "경기 - Gyeonggi-do",
    //     경상남도: "경남 - Gyeongsangnam-do",
    //     경상북도: "경북 - Gyeongsangbuk-do",
    //     광주광역시: "광주 - Gwangju",
    //     대구광역시: "대구 - Daegu",
    //     대전광역시: "대전 - Daejeon",
    //     부산광역시: "부산 - Busan",
    //     서울특별시: "서울 - Seoul",
    //     세종특별자치시: "세종 - Sejong",
    //     울산광역시: "울산 - Ulsan",
    //     인천광역시: "인천 - Incheon",
    //     전라남도: "전남 - Jeollanam-do",
    //     전라북도: "전북 - Jeollabuk-do",
    //     제주특별자치도: "제주 - Jeju-do",
    //     충청남도: "충남 - Chungcheongnam-do",
    //     충청북도: "충북 - Chungcheongbuk-do",
    // },
    // US: {
    //     AL: "Alabama",
    //     AK: "Alaska",
    //     AZ: "Arizona",
    //     AR: "Arkansas",
    //     CA: "California",
    //     CO: "Colorado",
    //     CT: "Connecticut",
    //     DE: "Delaware",
    //     DC: "District of Columbia",
    //     FL: "Florida",
    //     GA: "Georgia",
    //     HI: "Hawaii",
    //     ID: "Idaho",
    //     IL: "Illinois",
    //     IN: "Indiana",
    //     IA: "Iowa",
    //     KS: "Kansas",
    //     KY: "Kentucky",
    //     LA: "Louisiana",
    //     ME: "Maine",
    //     MD: "Maryland",
    //     MA: "Massachusetts",
    //     MI: "Michigan",
    //     MN: "Minnesota",
    //     MS: "Mississippi",
    //     MO: "Missouri",
    //     MT: "Montana",
    //     NE: "Nebraska",
    //     NV: "Nevada",
    //     NH: "New Hampshire",
    //     NJ: "New Jersey",
    //     NM: "New Mexico",
    //     NY: "New York",
    //     NC: "North Carolina",
    //     ND: "North Dakota",
    //     OH: "Ohio",
    //     OK: "Oklahoma",
    //     OR: "Oregon",
    //     PA: "Pennsylvania",
    //     PR: "Puerto Rico",
    //     RI: "Rhode Island",
    //     SC: "South Carolina",
    //     SD: "South Dakota",
    //     TN: "Tennessee",
    //     TX: "Texas",
    //     UT: "Utah",
    //     VT: "Vermont",
    //     VA: "Virginia",
    //     WA: "Washington",
    //     WV: "West Virginia",
    //     WI: "Wisconsin",
    //     WY: "Wyoming",
    // },
};
