import { MAX_FILES_UPLOAD } from "config/constant";

const Product = {
    CA: {
        hasTax: {
            type: "checkbox",
            name: "hasTax",
            value: true,
            label_trans: "input_hasTax",
            required: false,
        },
        status: {
            type: "choices",
            name: "status",
            label_trans: "input_status",
            trans: "choose",
            required: true,
        },
        image: {
            type: "text",
            name: "image",
            label_trans: "input_image",
            multiple: false,
            required: false,
            show: false,
        },
        gallery: {
            type: "file",
            name: "gallery",
            label_trans: "input_gallery",
            format: "image/jpg,image/jpeg,image/png",
            multiple: true,
            maxFiles: MAX_FILES_UPLOAD,
            required: true,
        },
        category: {
            type: "choices",
            name: "category",
            label_trans: "input_category",
            trans: "choose",
            required: true,
        },
        sequence: {
            type: "number",
            name: "sequence",
            value: 1,
            label_trans: "input_sequence",
            required: false,
        },
        title: {
            type: "text",
            name: "title",
            label_trans: "input_title",
            required: true,
        },
        measure: {
            type: "number",
            name: "measure",
            label_trans: "input_measure",
            required: true,
        },
        measureUnit: {
            type: "choices",
            name: "measureUnit",
            label_trans: "input_measureUnit",
            trans: "choose",
            required: true,
        },
        price: {
            type: "number",
            name: "price",
            label_trans: "input_price",
            required: true,
        },
        salePrice: {
            type: "number",
            name: "salePrice",
            label_trans: "input_salePrice",
            required: false,
        },
        inventory: {
            type: "number",
            name: "inventory",
            value: 100,
            label_trans: "input_inventory",
            required: true,
        },
        inventoryWarning: {
            type: "number",
            name: "inventoryWarning",
            value: 0,
            label_trans: "input_inventoryWarning",
            note_trans: "input_inventoryWarning_note",
            required: false,
        },
        description: {
            type: "textarea",
            name: "description",
            label_trans: "input_description",
            required: false,
        },
    },
    FR: {
        hasTax: {
            type: "checkbox",
            name: "hasTax",
            value: false,
            label_trans: "input_hasTax",
            required: false,
            show: false,
        },
        status: {
            type: "choices",
            name: "status",
            label_trans: "input_status",
            trans: "choose",
            required: true,
        },
        image: {
            type: "text",
            name: "image",
            label_trans: "input_image",
            multiple: false,
            required: false,
            show: false,
        },
        gallery: {
            type: "file",
            name: "gallery",
            label_trans: "input_gallery",
            format: "image/jpg,image/jpeg,image/png",
            multiple: true,
            maxFiles: MAX_FILES_UPLOAD,
            required: true,
            // note_trans: "input_image_note",
        },
        category: {
            type: "choices",
            name: "category",
            label_trans: "input_category",
            trans: "choose",
            required: true,
        },
        sequence: {
            type: "number",
            name: "sequence",
            value: 1,
            label_trans: "input_sequence",
            required: false,
        },
        title: {
            type: "text",
            name: "title",
            label_trans: "input_title",
            required: true,
        },
        measure: {
            type: "number",
            name: "measure",
            label_trans: "input_measure",
            required: true,
        },
        measureUnit: {
            type: "choices",
            name: "measureUnit",
            label_trans: "input_measureUnit",
            trans: "choose",
            required: true,
        },
        price: {
            type: "number",
            name: "price",
            label_trans: "input_price",
            required: true,
        },
        salePrice: {
            type: "number",
            name: "salePrice",
            label_trans: "input_salePrice",
            required: false,
        },
        inventory: {
            type: "number",
            name: "inventory",
            label_trans: "input_inventory",
            required: true,
        },
        inventoryWarning: {
            type: "number",
            name: "inventoryWarning",
            value: 0,
            label_trans: "input_inventoryWarning",
            note_trans: "input_inventoryWarning_note",
            required: false,
        },
        description: {
            type: "textarea",
            name: "description",
            label_trans: "input_description",
            required: false,
        },
    },
};

export default Product;
